import Head from "next/head";
import { Inter } from "next/font/google";
import ProductService from "@/services/product.service";
import { Product, Products } from "@/types/products/products.types";

export default function Home({ products }: { products: Products }) {
  return (
    <>
      <Head>
        <title>Louis Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {products.map((product) => (
          <div key={product.id}>
            <h2>{product.title}</h2>
            <p>{product.description}</p>
            <p>{product.price}</p>
          </div>
        ))}
      </main>
    </>
  );
}

export const getStaticProps = async () => {
  const products = await ProductService.getLastProducts();

  return {
    props: {
      products: products,
      revalidate: 60,
    },
  };
};
